### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SAA37** [JakobiObi/UWF-CIS495C-Spotd#52]
1. Navigate to AddAPetFragment
![screenshot_20180423-214029_spot d](https://user-images.githubusercontent.com/8855794/39163226-2ca3b424-473f-11e8-8628-aacf8c7c96c8.jpg)
2. Tap Actions button 
![screenshot_20180423-214038_samsung experience home](https://user-images.githubusercontent.com/8855794/39163231-35e153c0-473f-11e8-86e2-985caa8df934.jpg)

**Comment by SAA37** [comment]
Basically, tap Actions button without editing the Animal name, type, and status fields.

**Comment by abdwyer** [comment]
This has been fixed with PR #54
